config/routes.rb
Project::Application.routes.draw do
  resources :friendships

  resources :groups
  resources :saved_articles

  match 'shared_articles/sent' => 'shared_articles#sent'
  resources :shared_articles
  resources :articles
  match 'users/search' => 'users#search'
  match 'users/update_front_page' => 'users#update_front_page', :method => :post
  resources :users

  match 'sessions/destroy' => 'sessions#destroy'
  match 'sessions/new' => 'sessions#new'
  match 'sessions/create' => 'sessions#create'
  match 'frontpage' => 'front_page#index'
  
  root :to => 'users#new'
  
end

app/models/shared_article.rb
require 'net/http'

class SharedArticle < ActiveRecord::Base
  belongs_to :article
  has_and_belongs_to_many :users, :uniq => true
  belongs_to :shared_by, :class_name => "User", :foreign_key => "shared_by"
  validates_presence_of :article_id, :shared_by

  # Method to process the parameters produced by the new shared articles form
  def self.create_share(params)
    article = Article.find_or_create_by_url(params[:url])
    shared_article = SharedArticle.new
    shared_article.article_id = article.id
    shared_article.blurb = params[:blurb]
    shared_article.shared_by = User.find(params[:shared_by])
    shared_with = params[:users].split(',').map(&:strip).select{|s| !s.blank?}.map{|id| User.find(id) rescue nil}
    shared_with.each{ |user| shared_article.users << user unless user.nil? }
    return shared_article
  end
  

  
end

app/controllers/shared_articles_controller.rb
class SharedArticlesController < ApplicationController
  # GET /shared_articles
  # GET /shared_articles.json
  
  #force_ssl
  def index
    @shared_articles = @current_user.received_articles

    respond_to do |format|
      format.html
      format.json { render json: @shared_articles }
    end
  end

  # GET /shared_articles/1
  # GET /shared_articles/1.json
  def show
    @shared_article = SharedArticle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shared_article }
    end
  end

  # GET /shared_articles/new
  # GET /shared_articles/new.json
  def new
    @shared_article = SharedArticle.new
    
    if params[:article_id].present?
      @article=Article.find(params[:article_id]) rescue nil
    else
      flash.now[:notice] = 'Please enter a valid URL'
    end
    
    if params[:user_id].present?
      @user=User.find(params[:user_id]) rescue nil
    else
      flash.now[:notice] = 'Please enter a valid user'
    end

    respond_to do |format|
      format.html {render :partial => "new"}
      format.json { render json: @shared_article }
    end
  end

  # GET /shared_articles/1/edit
  def edit
    @shared_article = SharedArticle.find(params[:id])
  end

  # POST /shared_articles
  # POST /shared_articles.json
  def create
    @shared_article = SharedArticle.create_share(params)

    respond_to do |format|
      if @shared_article.save
        @article = Article.new
        format.html { render :partial => 'form', :notice => 'Article was succesfully shared!' }
        #format.json { render json: @shared_article, status: :created, location: @shared_article }
      else
        format.html { render :partial => "new", :notice => 'Article was not shared!'}
        #format.json { render json: @shared_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shared_articles/1
  # PUT /shared_articles/1.json
  def update
    @shared_article = SharedArticle.find(params[:id])

    respond_to do |format|
      if @shared_article.update_attributes(params[:shared_article])
        format.html { redirect_to @shared_article, notice: 'Shared article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shared_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shared_articles/1
  # DELETE /shared_articles/1.json
  def destroy
    @shared_article = SharedArticle.find(params[:id])
    @shared_article.destroy

    respond_to do |format|
      format.html { redirect_to shared_articles_url }
      format.json { head :ok }
    end
  end
  
  def sent
  end
end

app/helpers/shared_articles_helper.rb
module SharedArticlesHelper
end

app/views/shared_articles/_form.html.haml
.x-box-lightbox x
%h1.share-an-article-header Share an Article
%h3#article-title
  = link_to @article.title, @article.url if @article.present?
%p#notice
= form_tag "/shared_articles", :remote => true, :id => "new_shared_article", :method => "post" do
  -if @shared_article.present? && @shared_article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shared_article.errors.count, "error")} prohibited this article from being shared:"
      %ul
        - @shared_article.errors.full_messages.each do |msg|
          %li= msg

  %table
    %tr
      %th
        = label_tag :url
      %td
        = text_field_tag :url, @article ? @article.url : ""
    %tr
      %th
        = label_tag :share_with
      %td
        = text_field_tag :share_with, ""
        = hidden_field_tag :users, @shared_with ? @shared_with.id : ""
    %tr
      %th
      %td
        %ul#shared_with
          %li= @user.firstname + @user.lastname if @user 
    %tr
      %th
        = label_tag :blurb
      %td
        = text_area_tag :blurb
    .field
      = hidden_field_tag :shared_by, @current_user.id #? @current_user.id : 1
      = hidden_field_tag :article_id, @article ? @article.id : ""
    %tr
      %td
      %td
        = submit_tag 'Share', :class => "submit", :id => "share-an-article-button"

app/views/shared_articles/_new.html.haml
= render 'form'

app/views/shared_articles/_sent_articles.html.haml
%h1 Sent Articles
%table
  %tr
    
  -@current_user.sent_articles.order("created_at DESC").limit(10).each do |sent_article|
    %tr
      %td= link_to sent_article.article.title, sent_article.article.url
    %tr
      %td= sent_article.blurb
    %tr
      %td= link_to "Share Again", :controller => "articles", :action => :new, :id => @current_user.id
    %tr
      %td= raw "-----------------------------"
%br

app/views/shared_articles/_shared_articles.html.haml
%h1.shared-articles-header  Received Articles
-if @shared_articles.any?
  %ol#shared-article-list
    - @current_user.received_articles.order("created_at DESC").limit(10).each do |shared_article|
      %li.shared-article
        .close-box x
        %header
          %hgroup
            %h3= link_to "#{shared_article.shared_by.firstname} shared", shared_article.shared_by
            %h2= link_to shared_article.article.title, shared_article.article.url
        %p.blurb= shared_article.blurb
        %footer
          %p.share-this-button= link_to "Share This", :controller => "articles", :action => :new, :id => @current_user.id
    .clear
-else
  %p#notice You have none. Invite some friends to share with you!

app/views/shared_articles/edit.html.haml
%h1 Editing shared_article

= render 'form'

= link_to 'Show', @shared_article
\|
= link_to 'Back', shared_articles_path

app/views/shared_articles/index.html.haml
= render :partial => "shared_articles"

app/views/shared_articles/sent.html.haml
%p#notice= notice

= render 'sent_articles'

app/views/shared_articles/show.html.haml
%p#notice= notice

%p
  %b= @shared_article.shared_by.firstname + " says:"
  = @shared_article.blurb

= link_to 'Edit', edit_shared_article_path(@shared_article)
\|
= link_to 'Back', shared_articles_path