config/routes.rb
Project::Application.routes.draw do
  resources :friendships

  resources :groups
  resources :saved_articles

  match 'shared_articles/sent' => 'shared_articles#sent'
  resources :shared_articles
  resources :articles
  match 'users/search' => 'users#search'
  match 'users/update_front_page' => 'users#update_front_page', :method => :post
  resources :users

  match 'sessions/destroy' => 'sessions#destroy'
  match 'sessions/new' => 'sessions#new'
  match 'sessions/create' => 'sessions#create'
  match 'frontpage' => 'front_page#index'
  
  root :to => 'users#new'
  
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/new
  # GET /friendships/new.json
  def new
    @friendship = Friendship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/1/edit
  def edit
    @friendship = Friendship.find(params[:id])
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(params[:friendship])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render json: @friendship, status: :created, location: @friendship }
      else
        format.html { render action: "new" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friendships/1
  # PUT /friendships/1.json
  def update
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      if @friendship.update_attributes(params[:friendship])
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to friendships_url }
      format.json { head :ok }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.haml
= form_for @friendship do |f|
  -if @friendship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@friendship.errors.count, "error")} prohibited this friendship from being saved:"
      %ul
        - @friendship.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :friend_id
    = f.number_field :friend_id
  .actions
    = f.submit 'Save'

app/views/friendships/edit.html.haml
%h1 Editing friendship

= render 'form'

= link_to 'Show', @friendship
\|
= link_to 'Back', friendships_path

app/views/friendships/index.html.haml
%h1 Listing friendships

%table
  %tr
    %th User
    %th Friend
    %th
    %th
    %th

  - @friendships.each do |friendship|
    %tr
      %td= friendship.user_id
      %td= friendship.friend_id
      %td= link_to 'Show', friendship
      %td= link_to 'Edit', edit_friendship_path(friendship)
      %td= link_to 'Destroy', friendship, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Friendship', new_friendship_path

app/views/friendships/new.html.haml
%h1 New friendship

= render 'form'

= link_to 'Back', friendships_path

app/views/friendships/show.html.haml
%p#notice= notice

%p
  %b User:
  = @friendship.user_id
%p
  %b Friend:
  = @friendship.friend_id

= link_to 'Edit', edit_friendship_path(@friendship)
\|
= link_to 'Back', friendships_path